# Generated by Django 5.1.1 on 2024-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinPackingDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('first_fit', 'First Fit'), ('next_fit', 'Next Fit'), ('best_fit', 'Best Fit'), ('worst_fit', 'Worst Fit')], max_length=20)),
                ('bin_capacity', models.PositiveIntegerField()),
                ('item_list', models.TextField(help_text='Enter items as comma-separated values, e.g., 10, 20, 30')),
            ],
        ),
    ]
